# -*- coding: utf-8 -*-
"""板块级指标（斜率等）计算与落库。"""

from backend_core.board_metrics.sector_slope_store import (
    ALLOWED_SLOPE_BOARD_CODE_SOURCE,
    DEFAULT_SECTOR_SLOPE_LONG_WINDOW,
    DEFAULT_SECTOR_SLOPE_MID_SHORT_WINDOW,
    DEFAULT_SECTOR_SLOPE_SHORT_WINDOW,
    DEFAULT_SECTOR_SLOPE_ULTRA_SHORT_WINDOW,
    DEFAULT_SECTOR_SLOPE_WINDOW,
    DEFAULT_SLOPE_WINDOWS,
    compute_board_sector_slope_detail,
    compute_board_sector_slope_details_for_windows,
    ensure_board_daily_metrics_table,
    ensure_board_sector_slope,
    filter_board_codes_by_source,
    list_concept_board_codes,
    list_industry_board_codes,
    load_board_sector_slopes,
    load_board_sector_slopes_multi,
    normalize_member_limit,
    refresh_board_sector_slopes,
    resolve_slope_lookback,
    slope_strong_threshold_for_window,
    upsert_board_sector_slopes,
    write_slope_collect_log,
)

__all__ = [
    "ALLOWED_SLOPE_BOARD_CODE_SOURCE",
    "DEFAULT_SECTOR_SLOPE_LONG_WINDOW",
    "DEFAULT_SECTOR_SLOPE_MID_SHORT_WINDOW",
    "DEFAULT_SECTOR_SLOPE_SHORT_WINDOW",
    "DEFAULT_SECTOR_SLOPE_ULTRA_SHORT_WINDOW",
    "DEFAULT_SECTOR_SLOPE_WINDOW",
    "DEFAULT_SLOPE_WINDOWS",
    "compute_board_sector_slope_detail",
    "compute_board_sector_slope_details_for_windows",
    "ensure_board_daily_metrics_table",
    "ensure_board_sector_slope",
    "filter_board_codes_by_source",
    "list_concept_board_codes",
    "list_industry_board_codes",
    "load_board_sector_slopes",
    "load_board_sector_slopes_multi",
    "normalize_member_limit",
    "refresh_board_sector_slopes",
    "resolve_slope_lookback",
    "slope_strong_threshold_for_window",
    "upsert_board_sector_slopes",
    "write_slope_collect_log",
]
